server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://172.30.1.2:5432/postgres
    username: postgres
    password: rootp
    platform: postgresql
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update